export enum OperationStatus {
    SUCCESS = "Success",
    ERROR = "Error"
}

export enum ErrorCodes {
    ERR_FILE_NOT_FOUND = "ERR_FILE_NOT_FOUND",
    ERR_FILE_PARSING_FAILED = "ERR_FILE_PARSING_FAILED",
    ERR_HEADER_READ_FAILED = "ERR_HEADER_READ_FAILED",
    ERR_ELEMENT_NOT_FOUND = "ERR_ELEMENT_NOT_FOUND",
    ERR_UPLOAD_FAILED = "ERR_UPLOAD_FAILED",
}
